---
- name: "Play | Running roles"
  hosts: "localhost"
  gather_facts: "True"
  become: True
  vars:
    bool_strings:
      - "y"
      - "Y"
      - "yes"
      - "Yes"
      - "YES"
      - "n"
      - "N"
      - "no"
      - "No"
      - "NO"
      - "true"
      - "True"
      - "TRUE"
      - "false"
      - "False"
      - "FALSE"
      - "on"
      - "On"
      - "ON"
      - "off"
      - "Off"
      - "OFF"
    global_user: "{{ lookup('env', 'USER') }}"
    global_home: "{{ lookup('env', 'HOME') }}"
    global_editor: "{{ lookup('env', 'EDITOR') }}"
  pre_tasks:
    - name: "debug"
      debug:
        var: bool_strings

    - name: "Ensuring to not run as root"
      fail:
        msg: "This is not meant to be run as root. Please use a non root account and use --ask-become-pass to escalate privileges"
      when: global_user == "root"

    - name: "Ensuring host_vars folder exists"
      file:
        path: "{{ inventory_dir }}/host_vars"
        state: "directory"
  
    - name: "Ensuring host_vars file exists"
      file:
        path: "{{ inventory_dir }}/host_vars/localhost"
        state: "touch"
        modification_time: "preserve"
        access_time: "preserve"

    - pause:
        prompt: "Do you use this machine for work? (Yes/No)"
        echo: "True"
      register: "prompt_is_work"
      when: is_work is undefined
      until: prompt_is_work.user_input in bool_strings
      retries: 3
      delay: 0

    - set_fact:
        is_work: "{{ prompt_is_work.user_input }}"
      when: is_work is undefined

    - pause:
        prompt: "Do you use this machine privately? (Yes/No)"
        echo: "True"
      register: "prompt_is_private"
      when: is_private is undefined
      until: prompt_is_private.user_input in bool_strings
      retries: 3
      delay: 0

    - set_fact:
        is_private: "{{ prompt_is_private.user_input }}"
      when: is_private is undefined

    - pause:
        prompt: "Is this machine a laptop? (Yes/No)"
        echo: "True"
      register: "prompt_is_laptop"
      when: is_laptop is undefined
      until: prompt_is_laptop.user_input in bool_strings
      retries: 3
      delay: 0

    - set_fact:
        is_laptop: "{{ prompt_is_laptop.user_input }}"
      when: is_laptop is undefined

    - pause:
        prompt: "Please enter the path to the folder containing your ssh keys [Press enter to skip]" 
        echo: "True"
      register: "prompt_ssh_key_dir"
      when: is_ssh_key_imported is undefined
      until: prompt_ssh_key_dir.user_input is directory
      retries: 3
      delay: 0

    - set_fact:
        ssh_key_dir: "{{ prompt_ssh_key_dir.user_input }}"
      when: is_ssh_key_imported is undefined

    - pause:
        prompt: "Please enter the username that should be used for git"
        echo: "True"
      register: "prompt_git_username"
      when: git_username is undefined

    - set_fact:
        git_username: "{{ prompt_git_username.user_input }}"
      when: git_username is undefined

    - pause:
        prompt: "Please enter the email address that should be used for git"
        echo: "True"
      register: "prompt_git_email"
      when: git_email is undefined

    - set_fact:
        git_email: "{{ prompt_git_email.user_input }}"
      when: git_email is undefined

    - pause:
        prompt: "Please enter the private key name that should be used for git"
        echo: "True"
      register: "prompt_git_key_name"
      when: git_key_name is undefined

    - set_fact:
        git_key_name: "{{ prompt_git_key_name.user_input }}"
      when: git_key_name is undefined

    - pause:
        prompt: "Please enter the path to the folder containing your strongswan secrets [Press enter to skip]" 
        echo: "True"
      register: "prompt_strongswan_secret_dir"
      when: 
        - is_private | bool
        - is_strongswan_secret_imported is undefined
      until: prompt_strongswan_secret_dir is directory
      retries: 3
      delay: 0

    - set_fact:
        strongswan_secret_dir: "{{ prompt_strongswan_secret_dir.user_input }}"
      when: 
        - is_private | bool
        - is_strongswan_secret_imported is undefined

    - name: "Updating host_vars files"
      lineinfile:
        dest: "{{ inventory_dir }}/host_vars/localhost"
        regexp: "{{ var.name }}:"
        line: "{{ var.name }}: {{ var.value }}"
      loop_control:
        loop_var: "var"
      loop:
        - { "name": "is_work", "value": "{{ is_work }}" }
        - { "name": "is_private", "value": "{{ is_private }}" }
        - { "name": "is_laptop", "value": "{{ is_laptop }}" }
        - { "name": "git_username", "value": "{{ git_username }}" }
        - { "name": "git_email", "value": "{{ git_email }}" }
        - { "name": "git_key_name", "value": "{{ git_key_name }}" }



  tasks:
    - name: "Including common role"
      include_role:
        name: "common"

    - name: "Including work role"
      include_role:
        name: "work"
      when: is_work | bool
    
    - name: "Including private role"
      include_role:
        name: "private"
      when: is_private | bool
  
    - name: "Including laptop role"
      include_role:
        name: "laptop"
      when: is_laptop | bool



- name: "Play | Cleaning up"
  hosts: "localhost"
  become: True
  tasks:
    - name: "Removing orphaned packages"
      dnf:
        autoremove: True
...
