---
- name: "Play | Running roles"
  hosts: "localhost"
  become: True
  vars:
    global_home: "{{ lookup('env', 'HOME') }}"
    global_editor: "{{ lookup('env', 'EDITOR') }}"
  vars_prompt:
    - name: "is_work"
      prompt: "Do you use this machine for work?"
      private: False
    - name: "is_private"
      prompt: "Do you use this machine privately?"
      private: False
    - name: "is_laptop"
      prompt: "Is this machine a laptop?"
      private: "False"
    - name: "git_user_name"
      prompt: "Please enter the username that should be used for git"
      private: "False"
    - name: "git_email_address"
      prompt: "Please enter the email address that should be used for git"
      private: False

  tasks:
    - name: "Including common role"
      include_role:
        name: "common"

    - name: "Including work role"
      include_role:
        name: "work"
      when: is_work | bool
    
    - name: "Including private role"
      include_role:
        name: "private"
      when: is_private | bool
  
    - name: "Including laptop role"
      include_role:
        name: "laptop"
      when: is_laptop | bool



- name: "Play | Cleaning up"
  hosts: "localhost"
  become: True
  tasks:
    - name: "Removing orphaned packages"
      dnf:
        autoremove: True
...
