---
- block:
  - name: "Updating packages"
    dnf:
      name: "*"
      state: "latest"

  - name: "Updating flatpaks"
    command:
      cmd: "flatpak update --noninteractive"
    register: "flatpak_update_results"
    changed_when: "'Nothing to do' not in flatpak_update_results.stdout"

  - name: "Installing distribution gpg key package"
    dnf:
      name: "distribution-gpg-keys"
      state: "latest"

  - name: "Importing free RPM Fusion repository gpg key"
    rpm_key:
      key: "/usr/share/distribution-gpg-keys/rpmfusion/RPM-GPG-KEY-rpmfusion-free-fedora-{{ansible_distribution_major_version}}"
      state: "present"

  - name: "Importing non-free RPM Fusion repository gpg key"
    rpm_key:
      key: "/usr/share/distribution-gpg-keys/rpmfusion/RPM-GPG-KEY-rpmfusion-nonfree-fedora-{{ansible_distribution_major_version}}"
      state: "present"

  - name: "Adding free RPM Fusion repository"
    dnf:
      name: "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ansible_distribution_major_version}}.noarch.rpm"
      state: "present"

  - name: "Adding non-free RPM Fusion repository"
    dnf:
      name: "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ansible_distribution_major_version}}.noarch.rpm"
      state: "present"

  - name: "Removing filtered fedora flathub remote"
    flatpak_remote:
      name: "fedora"
      state: "absent"

  - name: "Removing filtered fedora flathub testing remote"
    flatpak_remote:
      name: "fedora-testing"
      state: "absent"

  - name: "Adding unfiltered flathub remote"
    flatpak_remote:
      name: "flathub"
      state: "present"
      flatpakrepo_url: "https://flathub.org/repo/flathub.flatpakrepo"

  - name: "Install multimedia codec packages"
    dnf:
      name:
        - "gstreamer1-plugins-base"
        - "gstreamer1-plugins-good-*"
        - "gstreamer1-plugins-bad-*"
        - "gstreamer1-plugin-openh264"
        - "gstreamer1-libav"
        - "lame*"
      exclude:
        - "gstreamer1-plugins-bad-free-devel"
        - "lame-devel"
      state: "latest"

  - name: "Installing git package"  # Must be installed already. This is here for consistency
    dnf:
      name: "git"
      state: "latest"

  - name: "Ensuring directory for git configuration exists"
    file:
      path: "{{ [global_home, '.config/git'] | path_join }}"
      state: "directory" 

  - name: "Configuring git"
    template:
      src: "{{ [playbook_dir, 'templates/git/config.j2'] | path_join }}"
      dest: "{{ [global_home, '.config/git/config'] | path_join }}"

  - name: "Installing ssh package"
    dnf:
      name: "openssh"
      state: "latest"

  - name: "Importing ssh keys"
    copy:
      src: "{{ item }}"
      dest: "{{ [global_home, '.ssh/'] | path_join }}"
      owner: "{{ global_user }}"
      mode: 0600
    with_fileglob: "{{ [ssh_key_dir, '*key*'] | path_join }}"
    when:
      - is_ssh_key_imported is undefined
      - ssh_key_dir != ""
    register: ssh_key_dir_results

  - name: "Configuring ssh"
    template:
      src: "{{ [playbook_dir, 'templates/ssh/config.j2'] | path_join }}"
      dest: "{{ [global_home, '.ssh/config'] | path_join }}"

  - name: "Updating host_vars files"
    lineinfile:
      dest: "{{ [inventory_dir, 'host_vars/localhost'] | path_join }}"
      regexp: "is_ssh_key_imported:"
      line: "is_ssh_key_imported: True"
    when:
      - ssh_key_dir_results is not failed
      - ssh_key_dir_results is not skipped

  - name: "Installing ansible package"  # Must be installed already. This is here for consistency
    dnf:
      name: "ansible"
      state: "latest"

  - name: "Installing neovim package"
    dnf:
      name: "neovim"
      state: "latest"

  - name: "Installing vlc flatpak"
    flatpak:
      name: "org.videolan.VLC"
      state: "present"

  - name: "Ensuring font directory exists"
    file:
      path: "{{ [global_home, '.fonts'] | path_join }}"
      state: "directory"
  
  - name: "Checking if Source Code Pro Nerd Font exists"
    stat:
      path: "{{ [global_home, '.fonts/SauceCodeProNerdFontMono-Regular.ttf'] | path_join }}"
    register: "nf_font_check"
  
  - name: "Installing Source Code Pro Nerd Font"
    when: not nf_font_check.stat.exists
    unarchive:
      src: "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.0/SourceCodePro.zip"
      dest: "{{ [global_home, '.fonts/'] | path_join }}"
      remote_src: "True"

  - name: "Configuring bash"
    template:
      src: "{{ [playbook_dir, 'templates/bash/bashrc.j2'] | path_join }}"
      dest: "{{ [global_home, '.bashrc'] | path_join }}"

  - name: "Installing zsh package"
    dnf:
      name: "zsh"
      state: "latest"

  - name: "Ensuring directory for zsh configuration exists"
    file:
      path: "{{ [global_home, '.config/zsh'] | path_join }}"
      state: "directory" 

  - name: "Configuring zsh"
    copy:
      src: "{{ item }}"
      dest: "{{ [global_home, '.config/zsh/'] | path_join }}"
    with_fileglob:
      - "{{ [playbook_dir, 'files/zsh/*'] | path_join }}"
      - "{{ [playbook_dir, 'files/zsh/.*'] | path_join }}"

  - name: "Installing powerline10k zsh plugin"
    git:
      repo: "https://github.com/romkatv/powerlevel10k.git"
      dest: "{{ [global_home, '.config/zsh/powerlevel10k'] | path_join }}"
      clone: True
      update: True
      depth: 1

  - name: "Installing syntax-highlighting zsh plugin"
    git:
      repo: "https://github.com/zsh-users/zsh-syntax-highlighting.git"
      dest: "{{ [global_home, '.config/zsh/zsh-syntax-highlighting'] | path_join }}"
      clone: True
      update: True

  - name: "Installing zsh-autosuggestions zsh plugin"
    git:
      repo: "https://github.com/zsh-users/zsh-autosuggestions"
      dest: "{{ [global_home, '.config/zsh/zsh-autosuggestions'] | path_join }}"
      clone: True
      update: True

  - name: "Installing alacritty package"
    dnf:
      name: "alacritty"
      state: "latest"

  - name: "Configuring alacritty"
    copy:
      src: "{{ item }}"
      dest: "{{ [global_home, '.config/alacritty/'] | path_join }}"
    with_fileglob: "{{ [playbook_dir, 'files/alacritty/*'] | path_join }}"

      #  - name: "Installing lightly kde application theme package"
      #    dnf:
      #      name: "lightly"
      #      state: "latest"
      #    register: kde_lightly_results
      #
      #  - name: "Installing catppuccin kde theme"
      #    git:
      #      repo: "https://github.com/catppuccin/kde"
      #      dest: "{{ [global_home, '.config/kde/catppuccin-kde'] | path_join }}"
      #      clone: True
      #      update: True
      #      depth: 1
      #    register: kde_catppuccin_results

  rescue:
    - set_fact: task_failed = True
...
