---
- block:
    ###########
    # Writing #
    ###########
    - name: "Installing full latex package"
      dnf:
        name: "texlive-scheme-full"
        state: "latest"

    #################
    # Communication #
    #################
    - name: "Installing discord flatpak"
      flatpak:
        name: "com.discordapp.Discord"
        state: "present"

    ########
    # VPNs #
    ########
    - name: "Installing strongswan package"
      dnf:
        name: "strongswan"
        state: "latest"

    - name: "Importing strongswan secrets"
      copy:
        src: "{{ item }}"
        dest: "/etc/strongswan/swanctl/conf.d/"
        owner: "root"
        mode: 0600
      register: strongswan_secret_dir_results
      when:
        - (is_strongswan_secret_imported is undefined) or (not is_strongswan_secret_imported)
        - strongswan_secret_dir is defined
      with_fileglob: "{{ [strongswan_secret_dir, '*.conf'] | path_join }}"

    - name: "Updating host_vars files"
      lineinfile:
        dest: "{{ [inventory_dir, 'host_vars/localhost'] | path_join }}"
        regexp: "is_strongswan_secret_imported:"
        line: "is_strongswan_secret_imported: True"
      when:
        - strongswan_secret_dir_results is not failed
        - strongswan_secret_dir_results is not skipped

    - name: "Configuring strongswan"
      copy:
        src: "{{ item }}"
        dest: "/etc/strongswan/swanctl/conf.d/"
        owner: "root"
        mode: 0640
      with_fileglob: "{{ [playbook_dir, 'files/strongswan/swanctl/*.conf'] | path_join }}"
      when:
        - is_strongswan_secret_imported is defined
        - is_strongswan_secret_imported | bool

    ############
    # Studying #
    ############
    - name: "Installing anki flatpak"
      flatpak:
        name: "net.ankiweb.Anki"
        state: "present"

    - name: "Adding qtrvsim package"
      tags:
        - manual
        - unsave
      dnf:
        name: "https://download.opensuse.org/repositories/home:/jdupak/Fedora_37/x86_64/qtrvsim-0.9.5-3.1.x86_64.rpm"
        state: "latest"
        disable_gpg_check: True

  rescue:
    - set_fact: task_failed = True
